apiVersion: apps/v1
kind: Deployment
metadata:
  name: school-chale-hum-app
  labels:
    app: school-chale-hum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: school-chale-hum
  template:
    metadata:
      labels:
        app: school-chale-hum
    spec:
      imagePullSecrets:
        - name: harbor-registry-secret
      containers:
        - image: harbor.arpansahu.me/library/school_chale_hum:latest
          name: school-chale-hum
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: school-chale-hum-secret
                  key: SECRET_KEY
            - name: DEBUG
              valueFrom:
                secretKeyRef:
                  name: school-chale-hum-secret
                  key: DEBUG
            - name: ALLOWED_HOSTS
              valueFrom:
                secretKeyRef:
                  name: school-chale-hum-secret
                  key: ALLOWED_HOSTS
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: school-chale-hum-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: school-chale-hum-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_STORAGE_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: school-chale-hum-secret
                  key: AWS_STORAGE_BUCKET_NAME
            - name: BUCKET_TYPE
              valueFrom:
                secretKeyRef:
                  name: school-chale-hum-secret
                  key: BUCKET_TYPE
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: school-chale-hum-secret
                  key: DATABASE_URL
            - name: REDISCLOUD_URL
              valueFrom:
                secretKeyRef:
                  name: school-chale-hum-secret
                  key: REDISCLOUD_URL
            - name: MAIL_JET_API_KEY
              valueFrom:
                secretKeyRef:
                  name: school-chale-hum-secret
                  key: MAIL_JET_API_KEY
            - name: MAIL_JET_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: school-chale-hum-secret
                  key: MAIL_JET_API_SECRET
            - name: DOMAIN
              valueFrom:
                secretKeyRef:
                  name: school-chale-hum-secret
                  key: DOMAIN
            - name: PROTOCOL
              valueFrom:
                secretKeyRef:
                  name: school-chale-hum-secret
                  key: PROTOCOL
          ports:
            - containerPort: 8013
              name: daphne