apiVersion: apps/v1
kind: Deployment
metadata:
  name: school-chale-hum-app
  labels:
    app: school-chale-hum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: school-chale-hum
  template:
    metadata:
      labels:
        app: school-chale-hum
    spec:
      imagePullSecrets:
        - name: harbor-registry-secret
      containers:
        - image: harbor.arpansahu.me/library/school_chale_hum:latest
          name: school-chale-hum
          envFrom:
            - secretRef:
                name: school-chale-hum-secret
          ports:
            - containerPort: 8001
              name: gunicorn