apiVersion: v1
kind: Service
metadata:
  name: school-chale-hum-service
spec:
  selector:
    app: school-chale-hum
  ports:
    - protocol: TCP
      port: 8013
      targetPort: 8013
      nodePort: 32013
  type: NodePort